{% set name = "django-tenants" %}
{% set version = "3.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6bc67c26be57f412e47c476261a977ef0ef74ec3740d50fd1eb6b69cb072eb03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=2.1,<6

test:
  imports:
    - django_tenants
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-tenants/django-tenants
  summary: Tenant support for Django using PostgreSQL schemas.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
