{% set name = "django-tenants" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 81a4cd54695b7e561ec89dbcf952262d5643cbbfc3c92d184bb9698e857c529d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=2.1,<6.1
    # - psycopg <3.3,>=3.2.1
    # - gunicorn ==23
    # - coverage 

test:
  imports:
    - django_tenants
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-tenants/django-tenants
  summary: Tenant support for Django using PostgreSQL schemas.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
